import type { Project } from "@/types/notion";

export const dummyProjects: Project[] = [
  {
    id: "dummy-1",
    title: "개인 포트폴리오 웹사이트",
    description: "Notion을 CMS로 활용한 개인 포트폴리오 사이트",
    category: "Personal",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Notion API"],
    periodStart: "2024-03-01",
    periodEnd: null,
    status: "진행중",
    githubUrl: "https://github.com/example/portfolio",
    demoUrl: "https://portfolio.example.com",
    lastEditedTime: "2024-06-01T09:00:00.000Z",
  },
  {
    id: "dummy-2",
    title: "팀 협업 태스크 관리 툴",
    description: "실시간 동기화를 지원하는 팀 단위 태스크 관리 웹 애플리케이션",
    category: "Team",
    techStack: ["React", "Node.js", "PostgreSQL", "Socket.io"],
    periodStart: "2023-09-01",
    periodEnd: "2024-02-28",
    status: "완료",
    githubUrl: "https://github.com/example/task-manager",
    demoUrl: null,
    lastEditedTime: "2024-03-01T12:00:00.000Z",
  },
  {
    id: "dummy-3",
    title: "사내 데이터 파이프라인 자동화",
    description: "Python 기반 ETL 파이프라인으로 일일 리포트 자동 생성",
    category: "Company",
    techStack: ["Python", "FastAPI", "Docker", "Apache Airflow"],
    periodStart: "2023-04-01",
    periodEnd: "2023-10-31",
    status: "유지보수",
    githubUrl: null,
    demoUrl: null,
    lastEditedTime: "2024-01-15T08:30:00.000Z",
  },
  {
    id: "dummy-4",
    title: "커뮤니티 블로그 플랫폼",
    description: "Supabase 백엔드를 활용한 SSR 기반 커뮤니티 블로그",
    category: "Team",
    techStack: ["Vue", "Nuxt.js", "Supabase", "TypeScript"],
    periodStart: "2023-11-01",
    periodEnd: "2024-04-30",
    status: "완료",
    githubUrl: "https://github.com/example/blog-platform",
    demoUrl: "https://blog.example.com",
    lastEditedTime: "2024-05-10T14:00:00.000Z",
  },
  {
    id: "dummy-5",
    title: "크로스플랫폼 가계부 앱",
    description: "React Native로 제작한 iOS/Android 지원 가계부 모바일 앱",
    category: "Personal",
    techStack: ["React Native", "Expo", "TypeScript", "SQLite"],
    periodStart: "2024-01-15",
    periodEnd: "2024-05-31",
    status: "완료",
    githubUrl: null,
    demoUrl: null,
    lastEditedTime: "2024-06-05T10:00:00.000Z",
  },
];
